<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Sage.Scratch</AssemblyName>
    <RootNamespace>Highpoint.Sage.Scratch</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sage\Sage.csproj" />
    <ProjectReference Include="..\SageTestLib\Sage.Tests.csproj" />
  </ItemGroup>
</Project>