<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Sage.PFC</AssemblyName>
    <RootNamespace>Highpoint.Sage</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <NoWarn>CA5394</NoWarn>
    <WarningsAsErrors>$(WarningsAsErrors);CA1307;CA1309;CA1310</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sage\Sage.csproj" />
  </ItemGroup>
</Project>
